version: '3.9'

services:
  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/www/certbot:/var/www/certbot
    command: certonly --webroot --webroot-path=/var/www/certbot --email skygazer227@gmail.com --agree-tos --no-eff-email --force-renewal -d i7a207.p.ssafy.io
    # command: certificates
    # command: renew
