# Generated by Django 3.2.7 on 2022-07-14 03:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor', models.CharField(max_length=10)),
                ('floor_building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='building_floor', to='buildings.building')),
            ],
        ),
        migrations.CreateModel(
            name='Trashbin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('types', models.CharField(max_length=10)),
                ('current_amount', models.FloatField()),
                ('total_amount', models.FloatField()),
                ('last_discarded', models.DateTimeField(auto_now=True)),
                ('location_x', models.FloatField()),
                ('location_y', models.FloatField()),
                ('trashbin_floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floor_trashbin', to='buildings.floor')),
            ],
        ),
    ]
