# Generated by Django 3.2.12 on 2022-08-17 09:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CleanRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('map_path', models.TextField()),
                ('width', models.FloatField()),
                ('height', models.FloatField()),
                ('trashbin_size', models.FloatField()),
                ('order', models.IntegerField()),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floor', to='campus.building')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student_num', models.CharField(max_length=100)),
                ('belong', models.CharField(max_length=100)),
                ('rfid_num', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Trashbin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=200)),
                ('trash_type', models.CharField(choices=[('GER', 'General'), ('PET', 'Plastic'), ('CAN', 'Can'), ('GLA', 'Glass'), ('PPR', 'Paper')], default='GER', max_length=3)),
                ('amount', models.FloatField(default=0)),
                ('status', models.CharField(choices=[('SAF', 'Safe'), ('CAU', 'Caution'), ('WAR', 'Warning')], default='SAF', max_length=3)),
                ('location_x', models.FloatField()),
                ('location_y', models.FloatField()),
                ('is_connected', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('discard_users', models.ManyToManyField(related_name='discard_trashbin', through='campus.CleanRecord', to=settings.AUTH_USER_MODEL)),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trashbin', to='campus.floor')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trashbin', to='campus.group')),
            ],
        ),
        migrations.AddField(
            model_name='cleanrecord',
            name='trashbin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campus.trashbin'),
        ),
        migrations.AddField(
            model_name='cleanrecord',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
