# Generated by Django 3.2.12 on 2022-07-21 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('time', models.CharField(max_length=15)),
                ('empty_num', models.IntegerField()),
                ('use_num', models.IntegerField()),
                ('amount', models.FloatField()),
            ],
        ),
    ]
