# Generated by Django 3.2.12 on 2022-07-22 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campus', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('time', models.CharField(max_length=15)),
                ('empty_num', models.IntegerField()),
                ('use_num', models.IntegerField()),
                ('amount', models.FloatField()),
                ('trashbin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campus.trashbin')),
            ],
        ),
    ]
