# Generated by Django 3.2.12 on 2022-08-13 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildingdate',
            name='CAN',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='buildingdate',
            name='GLA',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='buildingdate',
            name='GRE',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='buildingdate',
            name='PET',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='buildingdate',
            name='PPR',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='floordate',
            name='CAN',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='floordate',
            name='GLA',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='floordate',
            name='GRE',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='floordate',
            name='PET',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='floordate',
            name='PPR',
            field=models.IntegerField(default=0),
        ),
    ]
