# Generated by Django 3.2.12 on 2022-08-11 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buildingdate',
            old_name='day',
            new_name='num',
        ),
        migrations.RenameField(
            model_name='floordate',
            old_name='day',
            new_name='num',
        ),
        migrations.RenameField(
            model_name='month',
            old_name='day',
            new_name='num',
        ),
        migrations.RenameField(
            model_name='trashbindate',
            old_name='day',
            new_name='num',
        ),
        migrations.RenameField(
            model_name='year',
            old_name='day',
            new_name='num',
        ),
    ]
